version: '3.0'

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/app

  action_server:
    build:
      context: .
      dockerfile: actions.Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - .:/app
